services:
    cowboys_infrastructure.cowboys_repository:
        class: Cowboys\Infrastructure\Cowboy\DoctrineCowboyRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    cowboys_infrastructure.user_provider:
        class: Cowboys\Infrastructure\Entity\DoctrineUserProvider
        arguments:
            - '@doctrine.orm.entity_manager'
