services:
    cowboys_app.register_handler:
        class: Cowboys\AppBundle\Handler\RegisterHandler
        arguments:
            - '@cowboys_infrastructure.user_provider'
            - '@security.password_encoder'
        tags:
            - { name: 'tactician.handler',  command: 'Cowboys\AppBundle\Command\RegisterCommand' }